version: '2'
services:
  web:
    image: albertalvarezbruned/odoo:6.1
    depends_on:
      - db
    ports:
      - "8071:8071"
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
#      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
#      - ./openerp-server.conf:/etc/odoo/openerp-server.conf
    environment:
      - USER=odoo
      - PASSWORD=myodoo
  db:
    image: postgres:9.6.2
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
