version: '2'
services:
  db:
    image: postgres:9.5.11-alpine
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=odoo
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./tmp/postgresql:/var/run/postgresql
    ports:
      - "5444:5432"
  web:
    image: albertalvarezbruned/odoo:6.1
    depends_on:
      - db
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./openerp-server.conf:/etc/odoo/openerp-server.conf
      - ./tmp/oe-sessions-odoo:/tmp/oe-sessions-odoo
      - ./tmp/lib/odoo:/var/lib/odoo
volumes:
  odoo-web-data:
  odoo-db-data:
