version: '2'
services:
  db:
    image: postgres:9.5.11-alpine
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./tmp/postgresql:/var/run/postgresql
      - ./sql/init.dump:/tmp/init.dump:ro
    ports:
      - "5444:5432"
  pgadmin:
# user admin pass admin
    links:
      - db:postgres
    image: zfil/pgadmin3
    volumes:
       - ./odoo-pgadmin/home:/home
       - ./odoo-pgadmin/root:/root
       - ./sql/init.dump:/tmp/init.dump:ro
    ports:
      - "5050:5050"
    environment:
      - DEFAULT_USER=odoo@odoo.com
      - DEFAULT_PASSWORD=odoo
      - DISPLAY=$DISPLAY_MAC
    restart: unless-stopped
  web:
    image: albertalvarezbruned/odoo:6_1_all
    depends_on:
      - db
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./openerp-server.conf:/etc/odoo/openerp-server.conf
      - ./tmp/oe-sessions-odoo:/tmp/oe-sessions-odoo
      - ./tmp/lib/odoo:/var/lib/odoo
volumes:
  odoo-web-data:
  odoo-db-data:
